# Generated by Django 5.2.4 on 2025-07-11 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand_type', models.CharField(choices=[('main', 'Main Brand'), ('competitor', 'Competitor Brand')], default='main', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('youtube_data', models.JSONField(blank=True, null=True)),
                ('naver_data', models.JSONField(blank=True, null=True)),
                ('market_summary', models.TextField(blank=True, null=True)),
                ('opportunity_insight', models.TextField(blank=True, null=True)),
                ('content_strategy', models.TextField(blank=True, null=True)),
                ('report_headline', models.CharField(blank=True, max_length=500, null=True)),
                ('gemini_analysis_raw', models.JSONField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.brand')),
            ],
        ),
    ]
