# Generated by Django 5.2.4 on 2025-07-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='distribution_strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
