# Generated by Django 5.2.4 on 2025-07-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_distribution_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to='wordclouds/'),
        ),
    ]
