# Generated by Django 5.2.4 on 2025-07-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_wordcloud_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='gemini_analysis_raw',
        ),
        migrations.AddField(
            model_name='report',
            name='projected_impact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
