# Generated by Django 5.2.4 on 2025-07-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_gemini_analysis_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='swot_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_persona',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
