# Generated by Django 5.2.4 on 2025-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_swot_analysis_report_target_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='associated_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='executive_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='key_interests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sentiment_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
