# Generated by Django 5.2.4 on 2025-07-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_associated_keywords_report_executive_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='executive_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
