# Generated by Django 5.2.4 on 2025-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_executive_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='competitor_brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
