# Generated by Django 5.2.4 on 2025-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_competitor_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='naver_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AddField(
            model_name='report',
            name='youtube_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
