# Generated by Django 5.2.4 on 2025-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_naver_chart_image_report_youtube_chart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sentiment_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='charts/'),
        ),
    ]
