# Generated by Django 5.2.4 on 2025-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_report_sentiment_chart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sentiment_chart_image',
        ),
        migrations.AddField(
            model_name='report',
            name='action_plan',
            field=models.JSONField(blank=True, help_text='Priority-based action plans with ROI/difficulty matrix.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='competitive_analysis',
            field=models.JSONField(blank=True, help_text='Competitor comparison, differentiation points, and attack points.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='customer_journey_strategy',
            field=models.JSONField(blank=True, help_text='5-stage customer journey analysis and strategy.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='positioning_map_data',
            field=models.JSONField(blank=True, help_text='Data for generating a 2x2 positioning map.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='risk_management',
            field=models.JSONField(blank=True, help_text='Key risks, contingency plans, and early warning indicators.', null=True),
        ),
    ]
