# Generated by Django 5.2.4 on 2025-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_report_sentiment_chart_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='action_plan',
        ),
        migrations.RemoveField(
            model_name='report',
            name='associated_keywords',
        ),
        migrations.RemoveField(
            model_name='report',
            name='competitive_analysis',
        ),
        migrations.RemoveField(
            model_name='report',
            name='content_strategy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='customer_journey_strategy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='distribution_strategy',
        ),
        migrations.RemoveField(
            model_name='report',
            name='executive_summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='key_interests',
        ),
        migrations.RemoveField(
            model_name='report',
            name='market_summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='naver_chart_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='naver_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='opportunity_insight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='positioning_map_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='projected_impact',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_headline',
        ),
        migrations.RemoveField(
            model_name='report',
            name='risk_management',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sentiment_analysis',
        ),
        migrations.RemoveField(
            model_name='report',
            name='swot_analysis',
        ),
        migrations.RemoveField(
            model_name='report',
            name='target_persona',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wordcloud_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='youtube_chart_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='youtube_data',
        ),
        migrations.AddField(
            model_name='report',
            name='generated_chart_paths',
            field=models.JSONField(blank=True, help_text='Paths to generated chart images', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_wordcloud_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Stores all raw data collected from APIs (YouTube, Naver, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(blank=True, help_text='The complete, structured report generated by Gemini, following the detailed schema.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='competitor_brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['brand', 'report_date'], name='reports_rep_brand_i_693a3e_idx'),
        ),
    ]
